[package]
name = "buran"
version = "0.1.0"
authors = ["vurpo <max@sandholm.org>"]

[dependencies]
gdk = "*"
glib = "*"
crossbeam = "0.3.0"
regex = "0.2.2"
lazy_static = "0.2.9"
serde = "1.0.15"
serde_json = "1.0.3"
serde_derive = "1.0.15"

[dependencies.gtk]
version = "0.2.0"
features = ["v3_10"]
